version: "3.9"

networks:
  default:
    name: Gojo-Network
    external: false

volumes:
  data-volume:
    name: Gojo-Volume
    driver: local

services:


  postgres:
    container_name: Gojo-DB
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=gojo_secret
      - POSTGRES_DB=gojo
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -h postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3
  

  queue:
    container_name: Gojo-Redis-Queue
    image: redis:7.2.4-alpine3.19
    restart: unless-stopped
    environment:
      - REDIS_PORT=6370
    networks:
      - default
    ports:
      - "6370:6370"
    command: redis-server --port 6370
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5


  cache:
    container_name: Gojo-Redis-Cache
    image: redis:7.2.4-alpine3.19
    restart: unless-stopped
    environment:
      - REDIS_PORT=6380
    networks:
      - default
    ports:
      - "6380:6380"
    command: redis-server --port 6380
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5


  meili:
    container_name: Gojo-Meilisearch
    image: getmeili/meilisearch:v1.6.0-rc.5
    restart: unless-stopped
    networks:
      - default
    ports:
      - "7700:7700"


  migration:
    container_name: Gojo-Migration
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - DB_SOURCE=postgresql://root:gojo_secret@postgres:5432/gojo?sslmode=disable
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy
        restart: true


  api:
    container_name: Gojo-Api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:gojo_secret@postgres:5432/gojo?sslmode=disable
      - REDIS_QUEUE_ADDRESS=queue:6370
      - REDIS_CACHE_ADDRESS=cache:6380
      - MEILISEATCH_ADDRESS=meili:7700
    networks:
      - default
    restart: unless-stopped
    depends_on:
      migration:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      queue:
        condition: service_started
      cache:
        condition: service_started