version: "3.9"
services:
  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=gojo_secret
      - POSTGRES_DB=gojo
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine3.18
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:gojo_secret@postgres:5432/gojo?sslmode=disable
      - REDIS_ADDRESS=redis:6379     
    depends_on:
      - postgres
      - redis
    command: [ "/gojo/main" ]
volumes:
  data-volume: