apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gojo-grpc-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"

spec:
  ingressClassName: nginx
  rules:
  - host: grpc.gojo.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gojo-api-service
            port:
              number: 90