apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gojo-http-ingress

spec:
  ingressClassName: nginx
  rules:
  - host: gojo.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gojo-api-service
            port:
              number: 80