name: Run unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:

      postgres:
        image: postgres:16.0-alpine3.18
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: gojo
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7.2-alpine3.18
        ports:
          - "6379:6379"

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v4.1.0
      with:
        go-version: '^1.21.1'

    - name: Install golang-migrate
      run: |
        go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
        which migrate

    - name: Run migrations
      run: make mgup

    - name: Test
      run: make test