name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        COMMIT_SHA=$(git rev-parse --short "${{ github.sha }}")
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:$COMMIT_SHA -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest -f ../../Dockerfile.migrate .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:$COMMIT_SHA
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
